version: '3.7'

services:
  crezco.api:
    image: ${DOCKER_REGISTRY-}crezcoapi
    depends_on:
      - "redis"
      - "mongodb"
    build:
      context: .
      dockerfile: Crezco.Api/Dockerfile
    links:
      - "redis" 

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
    - "27017:27017"
    volumes:
    - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: "redis"
    ports:
    - "6379:6379" 
    volumes:
    - redis_data:/data

volumes:
  redis_data:
  mongo_data:  
